spring.application.name=auth-service
server.port=8082

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://ctse:ctse@cluster0.lxm7rwc.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DATABASE:auth_service_db}

# JWT
app.jwt.secret=${JWT_SECRET:U3VwZXJTZWNyZXRLZXlTdXBlclNlY3JldEtleVN1cGVyU2VjcmV0S2V5MTIzNDU2}
app.jwt.issuer=${JWT_ISSUER:auth-service}
app.jwt.expiration-minutes=${JWT_EXP_MINUTES:60}

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# JSON response behaviour
spring.jackson.default-property-inclusion=non_null
