version: '3.8'

services:

  cart-order-service:
    build: .
    container_name: cart-order-service
    ports:
      - "8082:8082"
    environment:
      MONGODB_URI:          mongodb://mongodb:27017/cart_order_db
      JWT_SECRET:           ${JWT_SECRET}
      PRODUCT_CATALOG_URL:  ${PRODUCT_CATALOG_URL:-http://product-catalog-service:8081}
      PAYMENT_SERVICE_URL:  ${PAYMENT_SERVICE_URL:-http://payment-service:8083}
      AUTH_SERVICE_URL:     ${AUTH_SERVICE_URL:-http://auth-service:8080}
      INTERNAL_SERVICE_KEY: ${INTERNAL_SERVICE_KEY:-ctse-internal-secret-2024}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: cart-order-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cart_order_db
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    driver: bridge

volumes:
  mongodb_data:
