spring.application.name=payment-service
server.port=${SERVER_PORT:8090}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27019/payment_service_db}

service.cart-order.url=${CART_ORDER_SERVICE_URL:http://localhost:8083}
service.internal-key=${INTERNAL_SERVICE_KEY:ctse-internal-secret-2024}
app.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

payhere.sandbox=${PAYHERE_SANDBOX:true}
payhere.merchant-id=${PAYHERE_MERCHANT_ID:}
payhere.merchant-secret=${PAYHERE_MERCHANT_SECRET:}
payhere.currency=${PAYHERE_CURRENCY:USD}
payhere.notify-url=${PAYHERE_NOTIFY_URL:https://replace-me.ngrok-free.app/api/payment/notify}
payhere.return-url=${PAYHERE_RETURN_URL:http://localhost:3000/payment/success}
payhere.cancel-url=${PAYHERE_CANCEL_URL:http://localhost:3000/payment/cancel}
payhere.checkout-url=${PAYHERE_CHECKOUT_URL:https://sandbox.payhere.lk/pay/checkout}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.jackson.default-property-inclusion=non_null
