name: API Gateway CI/CD

on:
  push:
    branches: [main]
    paths:
      - "backend/api-gateway/**"
      - ".github/workflows/api-gateway.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/api-gateway/**"
      - ".github/workflows/api-gateway.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_backend-service-deploy.yml
    with:
      service_name: api-gateway
      service_dir: backend/api-gateway
      ecr_repository: ctse/api-gateway
      ecs_service: ${{ vars.ECS_SERVICE_API_GATEWAY }}
      aws_region: ${{ vars.AWS_REGION }}
      ecs_cluster: ${{ vars.ECS_CLUSTER }}
    secrets: inherit

