name: Auth Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "backend/auth-service/**"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/auth-service/**"
      - ".github/workflows/auth-service.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_backend-service-deploy.yml
    with:
      service_name: auth-service
      service_dir: backend/auth-service
      ecr_repository: ctse/auth-service
      ecs_service: ${{ vars.ECS_SERVICE_AUTH }}
      aws_region: ${{ vars.AWS_REGION }}
      ecs_cluster: ${{ vars.ECS_CLUSTER }}
    secrets: inherit

