name: Payment Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "backend/payment-service/**"
      - ".github/workflows/payment-service.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/payment-service/**"
      - ".github/workflows/payment-service.yml"
      - ".github/workflows/_backend-service-deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_backend-service-deploy.yml
    with:
      service_name: payment-service
      service_dir: backend/payment-service
      ecr_repository: ctse/payment-service
      ecs_service: ${{ vars.ECS_SERVICE_PAYMENT }}
      aws_region: ${{ vars.AWS_REGION }}
      ecs_cluster: ${{ vars.ECS_CLUSTER }}
    secrets: inherit
